### ISSUE TITLE
The open-vm-tools package prevent installing VMware Tools

### ISSUE THREAD

**Issue by it-praktyk** [geerlingguy/packer-ubuntu-1404#21]
I'm opening an issue here but it can be related to [ansible-role-packer-debian](https://github.com/geerlingguy/ansible-role-packer-debian).

I've updated the ubuntu1404.json to the newest iso 

```json
      "iso_urls": [
        "iso/ubuntu-14.04.5-server-amd64.iso",
        "http://releases.ubuntu.com/14.04/ubuntu-14.04.5-server-amd64.iso"
      ],
      "iso_checksum_type": "sha256",
      "iso_checksum": "dde07d37647a1d2d9247e33f14e91acb10445a97578384896b4e1d985f754cc1",
```

and try build vmware box.

I receive an error

```
    vmware-iso: TASK [geerlingguy.packer-debian : Run the VMware tools installer.] *************
    vmware-iso: fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "/tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default", "delta": "0:00:00.075623", "end": "2017-05-20 06:33:49.173368", "failed": true, "rc": 1, "start": "2017-05-20 06:33:49.097745", "stderr": "", "stderr_lines": [], "stdout": "The installer has detected an existing installation of open-vm-tools packages \non this system and will not attempt to remove and replace these user-space \napplications. It is recommended to use the open-vm-tools packages provided by \nthe operating system. If you do not want to use the existing installation of \nopen-vm-tools packages and use VMware Tools, you must uninstall the \nopen-vm-tools packages and re-run this installer.\nThe packages that need to be removed are:\nopen-vm-tools\nThe installer will next check if there are any missing kernel drivers. Type yes\nif you want to do this, otherwise type no [yes] \n\nFor kernels >= 4.0.0, the open-vm-tools packages need to be of version 10.0.0 \nor higher for VMware Host Guest Filessystem (vmhgfs) to function with VMware \nTools. Please upgrade open-vm-tools packages and rerun this installer, or \nuninstall open-vm-tools packages. Alternatively, you can disable using vmhgfs \nwhen VMware Tools are configured.\n\nEnter yes to proceed. [no] \n\nExecution aborted.", "stdout_lines": ["The installer has detected an existing installation of open-vm-tools packages ", "on this system and will not attempt to remove and replace these user-space ", "applications. It is recommended to use the open-vm-tools packages provided by ", "the operating system. If you do not want to use the existing installation of ", "open-vm-tools packages and use VMware Tools, you must uninstall the ", "open-vm-tools packages and re-run this installer.", "The packages that need to be removed are:", "open-vm-tools", "The installer will next check if there are any missing kernel drivers. Type yes", "if you want to do this, otherwise type no [yes] ", "", "For kernels >= 4.0.0, the open-vm-tools packages need to be of version 10.0.0 ", "or higher for VMware Host Guest Filessystem (vmhgfs) to function with VMware ", "Tools. Please upgrade open-vm-tools packages and rerun this installer, or ", "uninstall open-vm-tools packages. Alternatively, you can disable using vmhgfs ", "when VMware Tools are configured.", "", "Enter yes to proceed. [no] ", "", "Execution aborted."]}
    vmware-iso: to retry, use: --limit @/tmp/packer-provisioner-ansible-local/591fe151-7d7a-f700-ac81-1ae7390add50/main.retry
    vmware-iso:
```

I tried find in which step the open-vm-tools packages is installed to prevent it but without success.

When I initialized unattended installation of Ubuntu - using boot parameter and preseed.cfg file open-vm-tools were not installed.

I don't understand :-(

Can you look on this too? Thank you.
